version: "3.9"
services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: paulorcv/rinha-de-backend-2025:latest
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true