version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: rinha-postgres-local
    environment:
      POSTGRES_DB: rinha_payments
      POSTGRES_USER: rinha_user
      POSTGRES_PASSWORD: rinha_pass
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      POSTGRES_CONF_LISTEN_ADDRESSES: "*"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - local-backend

volumes:
  postgres_data:

networks:
  local-backend:
    driver: bridge
