
spring:
  application:
    name: rinha
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rinha_payments
    username: ${POSTGRES_USER:rinha_user}
    password: ${POSTGRES_PASSWORD:rinha_pass}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1
    properties:
      connect-timeout: 10
  reactor:
    netty:
      pool:
        max-connections: 50
      ioWorkerCount: 2
      http:
        server:
          max-queue-size: 100
      worker-count: 2
  webflux:
    max-in-memory-size: 2MB

server:
  port: 8080
payment:
  processor:
    main:
      healthcheck-url: ${PROCESSOR_DEFAULT_URL}/payments/service-health
      pay-url: ${PROCESSOR_DEFAULT_URL}/payments
    fallback:
      healthcheck-url: ${PROCESSOR_FALLBACK_URL}/payments/service-health
      pay-url: ${PROCESSOR_FALLBACK_URL}/payments
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.r2dbc: DEBUG
    br.com.paulorcv.rinha: DEBUG

# expondo rotas: /actuator/<health, info, metrics, prometheus>
management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo[http.server.requests]: "25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1500ms"
